### PR TITLE
Added resize option

### PR DESCRIPTION
**Pull request by arpitmisraw**
Issue - #11 
[link](https://arpitmisraw.github.io/OpenTerm/)

### CODE REVIEW

**Comment by gauthamzz** [comment]
apply it to the all three corners,expect the corner having the minimise and other buttons.
Also the themes should be part of the terminal,it should also move

**Comment by arpitmisraw** [comment]
Okay

**Comment by gauthamzz** [comment]
fix merge conflicts and finish issue fast. or closing this.

**Comment by arpitmisraw** [comment]
Okay

**Comment by aswanthkoleri** [comment]
@arpitmisraw  What is the update ?

**Pull request closed without merging**
