### PR TITLE
Added option for themes

### PR DESCRIPTION
**Pull request by arpitmisraw**
#16 
[link](https://arpitmisraw.github.io/OpenTerm/)

### CODE REVIEW

**Comment by gauthamzz** [comment]
Can you keep it on a drop down menu looking like a setting icon or named themes, on the right corner or something

**Comment by arpitmisraw** [comment]
Can I use bootstrap?

**Comment by gauthamzz** [comment]
I dont think thats a good idea for this project

**Comment by arpitmisraw** [comment]
@gauthamzz  I've added the dropdown menu. Please see the link again.

**Review by gauthamzz — APPROVED** [review]

**Pull request merged**
